services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: orion-back:local
    ports:
      - "8080:8080"
    environment:
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5000
    depends_on:
      - logstash
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    image: orion-front:local
    depends_on:
      - backend
    ports:
      - "8081:80"
      - "8443:443"
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.4
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - ./monitoring/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
    restart: unless-stopped
volumes:
  elasticsearch-data:
