sonar.sourceEncoding=UTF-8
sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src
sonar.test.inclusions=back/src/test/**/*,front/src/**/*.spec.ts
sonar.exclusions=front/src/**/*.spec.ts,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.java.binaries=back/build/classes/java/main
