sonar.sourceEncoding=UTF-8
sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src
sonar.java.binaries=back/build/classes/java/main
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
