sonar.sourceEncoding=UTF-8
sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src
sonar.test.inclusions=back/src/test/**/*,front/src/**/*.spec.ts
sonar.exclusions=front/src/**/*.spec.ts,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.java.binaries=back/build/classes/java/main
sonar.java.test.binaries=back/build/classes/java/test

sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info
sonar.java.libraries=back/build/sonar/runtime-libs/*.jar
sonar.java.test.libraries=back/build/sonar/test-libs/*.jar
